/*
** This file is intended only to allow zic.c to compile.
** Compilations made with this should not be distributed, since
** the below information is fairly useful in distributions.
**
** This file should always be distributed included in the
** Timezones::ZoneInfo repository, as it isn't autogenerated.
*/
#ifndef TZDEFAULT
# define TZDEFAULT "Etc/GMT" /* default zone */
#endif
#ifndef TZDIR
# define TZDIR "." /* TZif directory */
#endif
